# Generated by Django 3.1.7 on 2021-03-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodshophome', '0002_employee_order_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procucts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=50)),
                ('product_brand', models.CharField(max_length=50)),
                ('product_model', models.CharField(max_length=50)),
                ('product_description', models.CharField(max_length=100)),
                ('product_rating', models.FloatField()),
            ],
        ),
    ]
