# Generated by Django 3.1.7 on 2021-03-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodshophome', '0003_procucts'),
    ]

    operations = [
        migrations.AddField(
            model_name='procucts',
            name='prduct_img_path',
            field=models.CharField(default='not_available', max_length=1000),
        ),
    ]
