# Generated by Django 3.1.7 on 2021-04-12 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodshophome', '0004_procucts_prduct_img_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procucts',
            name='product_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
