# Generated by Django 3.1.7 on 2021-04-12 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('woodshophome', '0005_auto_20210412_0656'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('pricicin_unit', models.CharField(max_length=20)),
                ('product_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='woodshophome.procucts')),
            ],
        ),
    ]
